admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

home_page:
    path: /
    defaults: {_controller: FrontBundle:Default:index }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"