user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"